name: add-labels
on: 
  workflow_dispatch:

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6      
      - name: Synchronize labels
        uses: julb/action-manage-label@6ab8797f08ad692a9c1983de9b7c70fecaa927cf # v1
        with:
          from: .github/config/labels.yml
          skip_delete: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
