on:
  push: 
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@v2

    - name: 'Validate build'
      run: |
        npm install
        npm run build

    - name: 'Run L0 tests'
      run: |
        npm run test

    # validate if the dist folder has no changes that are not commited
    - name: 'Check for dist folder changes'
      run: |
        git diff --exit-code --name-only ${{ github.sha }} ${{ github.sha }}^
        if [ $? -eq 1 ]; then
          echo "dist folder has changes that are not commited"
          exit 1
        fi