on:
  push: 
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]        
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - name: 'Setup Node.js'
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: '20'

    - name: 'Validate build'
      run: |
        npm install
        npm run build

    - name: 'Run L0 tests'
      run: |
        npm run test

    # validate if the dist folder has no changes that are not commited
    - name: Check for uncommitted changes
      # do not run on Windows runnrs because it always has issues, perhaps line endings or something?
      if: runner.os != 'Windows'
      shell: pwsh
      run: |
        if ((git status --porcelain dist).Length -ne 0) {
          Write-Output "dist folder has changes that are not committed:"
          git status --porcelain dist
          exit 1
        }
        else {
          Write-Output "dist folder has no changes"
        }
