on:
  push: 
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]        
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@v4

    - name: 'Setup Node.js'
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 'Validate build'
      run: |
        npm install
        npm run build

    - name: 'Run L0 tests'
      run: |
        npm run test

    # validate if the dist folder has no changes that are not commited
    - name: Check for uncommitted changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "dist folder has changes that are not committed"
          exit 1
        fi